[book]
title = "demo-backend-go"
authors = ["Laurent VERDO√èA"]
language = "en"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
