---
openapi: '3.1.1'
info:
  title: demo-backend-go
  version: 0.1.0
servers:
  - url: 'http://localhost:8081/api/v0'
tags:
  - name: Authentication
  - name: Miscellaneous
# No authentication scheme declared
security: []
paths:
  /auth/session:
    post:
      tags:
        - Authentication
      summary: Create a new user session
      description: This endpoint is used to create a new user session.
      operationId: authNewSession
      # No security required for this endpoint as security start here !
      security: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: me@example.com
                password:
                  type: string
                  example: pa$$w0rd
              required:
                - email
                - password
        required: true
      responses:
        '200':
          description: Session successfully created
        '400':
          description: Bad request
        '403':
          description: Access denied
  /misc/version:
    get:
      tags:
        - Miscellaneous
      summary: Return the version
      operationId: getVersion
      # No security required for this endpoint as it is a public call
      security: []
      responses:
        '200':
          description: Build version returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  revision:
                    type: string
                    example: d4e5f6a
                    description: The revision identifier for the current commit or checkout
                  time:
                    type: string
                    format: date-time
                    example: 2024-10-06T09:25:27Z
                    description: The modification time associated with revision, in RFC3339 format
                  go:
                    type: string
                    example: go1.20.3
                    description: Version of the Go toolchain that built the binary
                  platform:
                    type: string
                    example: linux/amd64
                  modified:
                    type: boolean
                    description: True or false indicating whether the source tree had local modifications
